# These jobs are triggered automatically and they test the code and the examples.

jobs:
- job: 'test_ubuntu1604'
  condition: eq(variables['build_check'], 'false')
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      python -m pip install --upgrade pip setuptools
    failOnStderr: true
    displayName: 'Upgrade pip and setuptools'

  - script: pip install -e ".[tests, doc]"
    failOnStderr: true
    displayName: 'Install dev environment'

  - script: |
      pytest --cov gtda --cov-report xml
      flake8
    failOnStderr: true
    displayName: 'Test with pytest and flake8'

  - script: |
      pip install openml pandas
      pip install papermill
      cd examples
      for n in *.ipynb
      do
        papermill --start_timeout 2000 $n -
      done
    failOnStderr: true
    displayName: 'Test jupyter notebooks with papermill'


- job: 'test_macOS1014'
  condition: eq(variables['build_check'], 'false')
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      brew update
      brew install gcc boost
    failOnStderr: true
    displayName: 'Install gcc and boost'

  - script: |
      python -m pip install --upgrade pip setuptools
    failOnStderr: true
    displayName: 'Upgrade pip and setuptools'

  - script: pip install -e ".[tests, doc]"
    failOnStderr: true
    displayName: 'Install dev environment'

  - script: |
      pytest --cov gtda --cov-report xml
      flake8
    failOnStderr: true
    displayName: 'Test with pytest and flake8'

  - script: |
      pip install openml pandas
      pip install papermill
      cd examples
      for n in *.ipynb
      do
        papermill --start_timeout 2000 $n -
      done
    failOnStderr: true
    displayName: 'Test jupyter notebooks with papermill'


- job: 'test_win2016'
  condition: eq(variables['build_check'], 'false')
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python_ver: '35'
        python.version: '3.5'
      Python36:
        python_ver: '36'
        python.version: '3.6'
      Python37:
        python_ver: '37'
        python.version: '3.7'
      Python38:
        python_ver: '38'
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      python -m pip install --upgrade pip setuptools
    failOnStderr: true
    displayName: 'Upgrade pip and setuptools'

  - bash: |
      pycairo_url=$(python .azure-ci/python-igraph_dependencies_win.py '$(python_ver)' 'pycairo')
      igraph_url=$(python .azure-ci/python-igraph_dependencies_win.py '$(python_ver)' 'python-igraph')
      pip install "$pycairo_url" "$igraph_url"
    failOnStderr: true
    displayName: 'Install pycairo and python-igraph'

  - script: |
      pip install -e ".[tests, doc]"
    failOnStderr: true
    displayName: 'Install dev environment'

  - script: |
      pytest --cov gtda --cov-report xml
      flake8
    failOnStderr: true
    displayName: 'Test with pytest and flake8'

  - script: |
      pip install openml pandas
      pip install papermill
      cd examples
      FOR %%n in (*.ipynb) DO (papermill --start_timeout 2000 %%n -)
    failOnStderr: true
    displayName: 'Test jupyter notebooks with papermill'


# These jobs are triggered manually and they test the code and the examples and build the wheels and docs.

- job: 'manylinux2010'
  condition: eq(variables['build_check'], 'true')
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '35'
        python.version: '3.5'
      Python36:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '36'
        python.version: '3.6'
      Python37:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '37'
        python.version: '3.7'
      Python38:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '38'
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: |
      sed -i "s/'giotto-tda'/'giotto-tda-nightly'/1" setup.py
      sed -i "s/__version__.*/__version__ = '$(Build.BuildNumber)'/1" gtda/_version.py
      cat gtda/_version.py
    failOnStderr: true
    condition: eq(variables['nightly_check'], 'true')
    displayName: 'Change name to giotto-tda-nightly'

  - task: Bash@3
    inputs:
      filePath: .azure-ci/manylinux2010/run_ci.sh
      failOnStderr: false
    env:
      python_ver: $(python_ver)
    displayName: 'Run the docker, install and uninstall dev environment, test with pytest and flake8, build the wheels'

  - script: |
      python -m pip install --upgrade pip
    displayName: 'Upgrade pip and setuptools'

  - script: pip install dist/*.whl
    failOnStderr: true
    displayName: 'Install the wheels'

  - script: |
      pip install pytest pytest-cov pytest-azurepipelines pytest-benchmark flake8 hypothesis
      mkdir tmp_test_cov
      cd tmp_test_cov
      pytest --pyargs gtda --ignore-glob='*externals*' --no-cov --no-coverage-upload
    failOnStderr: true
    displayName: 'Test the wheels with pytest'

  - script: |
      pip install openml pandas
      pip install papermill
      cd examples
      for n in *.ipynb
      do
        papermill --start_timeout 2000 $n -
      done
    failOnStderr: true
    displayName: 'Test the wheels on jupyter notebooks with papermill'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel_and_doc'

  - bash: |
      pip install twine
      for f in dist/*linux* ; do sudo mv "$f" "${f/linux/manylinux2010}"; done
      twine upload -u giotto-learn -p $(pypi_psw) --skip-existing dist/*
    condition: eq(variables['nightly_check'], 'true')
    displayName: 'Upload nightly wheels to PyPI'


- job: 'macOS1014'
  condition: eq(variables['build_check'], 'true')
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: |
      sed -i.bak "s/'giotto-tda'/'giotto-tda-nightly'/1" setup.py
      rm setup.py.bak
      sed -i.bak "s/__version__.*/__version__ = '$(Build.BuildNumber)'/1" gtda/_version.py
      cat gtda/_version.py
      rm gtda/_version.py.bak
    failOnStderr: true
    condition: eq(variables['nightly_check'], 'true')
    displayName: 'Change name to giotto-tda-nightly'

  - script: |
      brew update
      brew install gcc boost
    failOnStderr: true
    displayName: 'Install gcc and boost'

  - script: |
      python -m pip install --upgrade pip setuptools
    failOnStderr: true
    displayName: 'Upgrade pip and setuptools'

  - script: pip install -e ".[tests, doc]"
    failOnStderr: true
    displayName: 'Install dev environment'

  - script: |
      pip uninstall -y giotto-tda
    condition: eq(variables['nightly_check'], 'false')
    failOnStderr: true
    displayName: 'Uninstall giotto-tda dev'

  - script: |
      pip uninstall -y giotto-tda-nightly
    condition: eq(variables['nightly_check'], 'true')
    failOnStderr: true
    displayName: 'Uninstall giotto-tda-nightly dev'

  - script: |
      pytest --cov gtda --cov-report xml
      flake8
    failOnStderr: true
    displayName: 'Test with pytest and flake8'

  - script: |
      pip install wheel
      python setup.py sdist bdist_wheel
    failOnStderr: false
    displayName: 'Build the wheels'

  - script: pip install dist/*.whl
    failOnStderr: true
    displayName: 'Install the wheels'

  - script: |
      mkdir tmp_test_cov
      cd tmp_test_cov
      pytest --pyargs gtda --ignore-glob='*externals*' --no-cov --no-coverage-upload
    failOnStderr: true
    displayName: 'Test the wheels with pytest'

  - script: |
      pip install openml pandas
      pip install papermill
      cd examples
      for n in *.ipynb
      do
        papermill --start_timeout 2000 $n -
      done
    failOnStderr: true
    displayName: 'Test the wheels on jupyter notebooks with papermill'

  - script: |
      cd doc/
      make html
    failOnStderr: true
    displayName: 'Build sphinx doc'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: doc/build
      includeRootFolder: true
      archiveType: 'zip'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive doc'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel_and_doc'

  - bash: |
      pip install twine
      twine upload -u giotto-learn -p $(pypi_psw) --skip-existing dist/*
    condition: eq(variables['nightly_check'], 'true')
    displayName: 'Upload nightly wheels to PyPI'


- job: 'win2016'
  condition: eq(variables['build_check'], 'true')
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python_ver: '35'
        python.version: '3.5'
      Python36:
        python_ver: '36'
        python.version: '3.6'
      Python37:
        python_ver: '37'
        python.version: '3.7'
      Python38:
        python_ver: '38'
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: |
      sed -i "s/'giotto-tda'/'giotto-tda-nightly'/1" setup.py
      sed -i "s/__version__.*/__version__ = '$(Build.BuildNumber)'/1" gtda/_version.py
      cat gtda/_version.py
    failOnStderr: true
    condition: eq(variables['nightly_check'], 'true')
    displayName: 'Change name to giotto-tda-nightly'

  - script: |
      python -m pip install --upgrade pip setuptools
    failOnStderr: true
    displayName: 'Upgrade pip and setuptools'

  - bash: |
      pycairo_url=$(python .azure-ci/python-igraph_dependencies_win.py '$(python_ver)' 'pycairo')
      igraph_url=$(python .azure-ci/python-igraph_dependencies_win.py '$(python_ver)' 'python-igraph')
      pip install "$pycairo_url" "$igraph_url"
    failOnStderr: true
    displayName: 'Install pycairo and python-igraph'

  - script: |
      pip install -e ".[tests, doc]"
    failOnStderr: true
    displayName: 'Install dev environment'

  - script: |
      pip uninstall -y giotto-tda
    condition: eq(variables['nightly_check'], 'false')
    failOnStderr: true
    displayName: 'Uninstall giotto-tda dev'

  - script: |
      pip uninstall -y giotto-tda-nightly
    condition: eq(variables['nightly_check'], 'true')
    failOnStderr: true
    displayName: 'Uninstall giotto-tda-nightly dev'

  - script: |
      pytest --cov gtda --cov-report xml
      flake8
    failOnStderr: true
    displayName: 'Test with pytest and flake8'

  - bash: |
      sed -i $'s/\r$//' README.rst
      pip install wheel
      python setup.py sdist bdist_wheel
    failOnStderr: false
    displayName: 'Build the wheels'

  - bash: pip install dist/*.whl
    failOnStderr: true
    displayName: 'Install the wheels'

  - bash: |
      mkdir tmp_test_cov
      cd tmp_test_cov
      pytest --pyargs gtda --ignore-glob='*externals*' --no-cov --no-coverage-upload
    failOnStderr: true
    displayName: 'Test the wheels with pytest'

  - script: |
      cd examples
      pip install openml pandas
      pip install papermill
      FOR %%n in (*.ipynb) DO (papermill --start_timeout 2000 %%n -)
    failOnStderr: true
    displayName: 'Test jupyter notebooks with papermill'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel_and_doc'

  - bash: |
      pip install twine
      twine upload -u giotto-learn -p $(pypi_psw) --skip-existing dist/*
    failOnStderr: true
    condition: eq(variables['nightly_check'], 'true')
    displayName: 'Upload nightly wheels to PyPI'
